version: '3.4'

services:
  crudsqlite3django:
    image: djangoecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgresdb
    env_file:
      - .env
    ports:
      - "${DJANGO_LOCAL_PORT}:${DJANGO_DOCKER_PORT}"
    environment:
      - DB_HOST=${DBHOST}
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASSWORD}
      - DB_NAME=${DATABASE}
      - DB_PORT=${DBPORT}

  postgresdb:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
