version: '3.4'

services:
  crudsqlite3django:
    image: djangoecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgresdb
    env_file:
      - .env
    ports:
      - "${DJANGO_LOCAL_PORT}:${DJANGO_DOCKER_PORT}"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DB_NAME=${POSTGRES_DB_DATABASE}
      - DB_PORT=${POSTGRES_DB_DOCKER_PORT}

  postgresdb:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_DATABASE}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
